# Site settings
title: One For The Road
email: your-email@domain.com
header-img: img/home-bg.jpg
copyright_name: Sam Wong
description: > # this means to ignore newlines until "baseurl:"
  "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: onefortheroad/onefortheroad.github.io
twitter_username: twitter_username
github_username:  github_username
facebook_username:  facebook_username
email_username:  email_username

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
# gems: [jekyll-paginate, jekyll-feed]
gem 'github-pages', group: :jekyll_plugins
exclude:
  - Gemfile
  - Gemfile.lock
  - "*.bat"
  - "*.py"
  - "*.ipynb"
  - "_drafts/data"
  - "less"
  - "hi-res"
