# Site settings
title: One For The Road
email: samhwwong@gmail.com
header-img: img/home-bg.jpg
copyright_name: Sam Wong
description: The best Data Analytics and Data Science tutorials, written for beginners using Python and pandas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://onefortheroad.github.io"
repository: onefortheroad/onefortheroad.github.io
linkedin_username: sam-wong-p-eng-73696b87
twitter_username: SirSamelot
github_username:  OneForTheRoad
facebook_username:
email_username:  samhwwong@gmail.com
disqus:
  shortname: one-for-the-road

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
gems: [jekyll-feed]
gem 'github-pages', group: :jekyll_plugins
exclude:
  - Gemfile
  - Gemfile.lock
  - "*.bat"
  - "*.py"
  - "*.ipynb"
  - "_drafts/data"
  - "less"
  - "hi-res"
